name: main
on: [push]

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Run Actions Template
    steps:
      # To use this repository's private action,
      # you must check out the repository

      - name: Generate Directory Listings
        uses: alvaloper/dms1@main
        with:
          FOLDER: data

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5

  deploy:
    needs: pages-directory-listing
    permissions:
      pages: write      # to deploy to Pages
   

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.0
